service: product-service

provider: 
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-1
  stage: dev

plugins:
  - serverless-esbuild
  - serverless-auto-swagger

custom:
  esbuild:
    config: './esbuild.config.js'
  # documentation: ${file(./swagger.yml)}

functions:
  getProductsList:
    handler: getProductsList/handler.handler
    events:
      - http:
          path: products
          method: get
          cors: true
  getProductsById:
    handler: getProductsById/handler.handler
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
