---
openapi: 3.0.0
info:
  title: Shop Service API
  description: This is a simple API
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/Shodlik-Shomuratov/ShopService/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://yeasirhhk2.execute-api.ap-southeast-1.amazonaws.com/dev
  description: Product Service
tags:
- name: Products
  description: Get all products and get products by id
paths:
  /products:
    get:
      tags:
      - Products
      summary: Get all products
      operationId: Get all products
      responses:
        "200":
          description: All products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
  /products/{productId}:
    get:
      tags:
      - Products
      summary: Get all products
      operationId: Get single products
      parameters:
      - name: productId
        in: path
        description: Product Id
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
components:
  schemas:
    Products:
      required:
      - id
      type: object
      properties:
        id:
          type: number
          example: 1
        title:
          type: string
          example: Product One
        description:
          type: string
          example: New product
        price:
          type: number
          example: 1000
